### ISSUE TITLE
Power spectra plot has weird  y ticks

### ISSUE THREAD

**Issue by xanderladd** [xanderladd/nma_motor_imagery#4]
see line `ax.yaxis.set_minor_formatter(mticker.ScalarFormatter()` in `analyze_freqs_and_powers` for first attempt to triage.

**Comment by mandarmp** [comment]
Fix in commit : 9184a9291cdd9c443cd11a1d907e9d077aeae760

    plt.vlines(freqs[np.argmax(powers)], 0,np.max(powers) , linestyle="dashed")
    plt.hlines(np.max(powers), 0, freqs[np.argmax(powers)], linestyle="dashed")
    ax.set_xticks([freqs[np.argmax(powers)]])
